{{- if eq .Values.master.kind "Deployment" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "buildbot.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: buildbot-master
spec:
{{ include "buildbot.master" . | indent 2 }}
      - name: buildbot-master-dir
        emptyDir: {}
{{- end }}
