{{- $buildbotWorker := (dict "Release" (dict "Name" .Release.Name) "Chart" (dict "Name" "buildbot-worker") "Values" (index .Values "buildbot-worker")) }}
{{- $crossbar := (dict "Release" (dict "Name" .Release.Name) "Chart" (dict "Name" "crossbar") "Values" (index .Values "crossbar")) }}
{{- if not .Values.config.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildbot.fullname" . }}-master.cfg
  labels:
    app.kubernetes.io/name: {{ include "buildbot.name" . }}
    helm.sh/chart: {{ include "buildbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: buildbot-master
data:
  master.cfg: |-
    # -*- python -*-
    # ex: set filetype=python:

    import os
    from buildbot.plugins import *

    # This is the dictionary that the buildmaster pays attention to. We also use
    # a shorter alias to save typing.
    c = BuildmasterConfig = {}


    ####### SECRETS
    c['secretsProviders'] = [
{{- if .Values.secret.values }}
        secrets.SecretInAFile(dirname="/var/lib/buildbot-secret/{{ .Release.Name }}-secret/..data"),
{{- end }}
{{- range .Values.secret.extraFileSecret }}
        secrets.SecretInAFile(dirname="/var/lib/buildbot-secret/buildbot-secret-{{ . }}/..data"),
{{- end }}
{{- range .Values.secret.extraFileSecret }}
        {{ . }},
{{- end }}
    ]

    ####### WORKERS

    # The 'workers' list defines the set of recognized workers. Each element is
    # a Worker object, specifying a unique worker name and password.  The same
    # worker name and password must be configured on the worker.
    c['workers'] = [
        worker.Worker(
            '{{ include "buildbot-worker.fullname" $buildbotWorker }}-{0}'.format(worker_id),
            password=os.environ['WORKERPASS'],
        )
        for worker_id in range(int(os.environ.get('NUM_WORKERS', 1)))
    ]
{{- if or .Values.crossbar.forceURL .Values.crossbar.enabled }}
    c['mq'] = {
        'type': 'wamp',
{{- if .Values.crossbar.forceURL }}
        'router_url': "{{ .Values.crossbar.forceURL }}",
{{- else }}
        'router_url': 'ws://{{ include "crossbar.fullname" $crossbar }}:{{ .Values.crossbar.service.port }}/ws',
{{- end }}
        'realm': 'realm1',
    }
{{- end }}
    c['multiMaster'] = True

    # 'protocols' contains information about protocols which master will use for
    # communicating with workers. You must define at least 'port' option that workers
    # could connect to your master with this protocol.
    # 'port' must match the value configured into the workers (with their
    # --master option)
    c['protocols'] = {'pb': {'port': {{ .Values.servicePB.port }}}}

    ####### CHANGESOURCES

    c['change_source'] = [
{{- range .Values.config.changeSource }}
{{ . | indent 8 }},
{{- end }}
    ]

    ####### SCHEDULERS

    # Configure the Schedulers, which decide how to react to incoming changes.  In this
    # case, just kick off a 'runtests' build

    c['schedulers'] = [
{{- range .Values.config.schedulers }}
{{ . | indent 8 }},
{{- end }}
    ]
    ####### BUILDERS

    # The 'builders' list defines the Builders, which tell Buildbot how to perform a build:
    # what steps, and which workers can execute them.  Note that any particular build will
    # only take place on one worker.

{{- range .Values.config.factories }}
{{ . | indent 4 }}
{{- end }}

    c['builders'] = [
{{- range .Values.config.builders }}
{{ . | indent 8 }},
{{- end }}
    ]

    ####### BUILDBOT SERVICES

    # 'services' is a list of BuildbotService items like reporter targets. The
    # status of each build will be pushed to these targets. buildbot/reporters/*.py
    # has a variety to choose from, like IRC bots.

    c['services'] = [
{{- range .Values.config.services }}
{{ . | indent 8 }},
{{- end }}
    ]
    ####### PROJECT IDENTITY

    # the 'title' string will appear at the top of this buildbot installation's
    # home pages (linked to the 'titleURL').

    c['title'] = '{{ .Values.config.title }}'
    c['titleURL'] = '{{ .Values.config.titleURL }}'
    c['buildbotNetUsageData'] = '{{ .Values.config.buildbotNetUsageData }}'

    # the 'buildbotURL' string should point to the location where the buildbot's
    # internal web server is visible. This typically uses the port number set in
    # the 'www' entry below, but with an externally-visible host name which the
    # buildbot cannot figure out without some help.

    c['buildbotURL'] = os.environ.get('BUILDBOT_MASTER_URL', 'http://localhost:{{ .Values.serviceUI.port }}/')

    # minimalistic config to activate new web UI
    c['www'] = dict(port={{ .Values.serviceUI.port }},
                    plugins=dict(waterfall_view={}, console_view={}))

    ####### DB URL

    c['db'] = {
        # This specifies what database buildbot uses to store its state
{{- if .Values.db.forceURL }}
        'db_url': "{{ .Values.db.forceURL }}".format(**os.environ)
{{- else }}
        'db_url' : "postgresql+psycopg2://{PG_USERNAME}:{PG_PASSWORD}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.postgresDatabase }}".format(**os.environ)
{{- end }}
    }
{{- end }}
